security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Utilisateur:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username
