parameters:
    locale: 'en'
    faker_locale: 'en_GB'
    app_locales: ['fr', '%locale%']
    app_locales_regex: 'fr|%locale%'
    image_directory: '%kernel.project_dir%/public/uploads/images'
    video_directory: '%kernel.project_dir%/public/uploads/videos'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\EventSubscriber\LocaleSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\Serializer\FormExceptionNormalizer:
        tags: ['serializer.normalizer']
    
    App\Factory\NormalizerFactory:
        arguments: [!tagged serializer.normalizer]
        public: true